### ISSUE TITLE
No Webmaps for constructionstation and cryostation

### ISSUE THREAD

**Issue by MaltVinegar** [SinguloStation13/SinguloStation13#22]
## Reproduction:

Click `View Webmap` button in `OOC` tab during a round with either of the Singulo maps and you get `The current map is either invalid or unavailable. Open an issue on the github.`

**Comment by KubeRoot** [comment]
The webmap link is currently pointing to the beestation link; we actually do have webmaps for those map, back from old singulocode, so after updating the link it should open those.

It seems like the maps updated for the new codebase, which is presumably a side effect of taking over the URL from the old repo with the new one. (I told you something would do that :P)
